//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 12:43:00 PM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for chatKorisnikXML complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="chatKorisnikXML">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="idChata" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="idKorisnika" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "chatKorisnikXML", propOrder = {
    "idChata",
    "idKorisnika"
})
public class ChatKorisnikXML {

    protected long idChata;
    protected long idKorisnika;

    /**
     * Gets the value of the idChata property.
     * 
     */
    public long getIdChata() {
        return idChata;
    }

    /**
     * Sets the value of the idChata property.
     * 
     */
    public void setIdChata(long value) {
        this.idChata = value;
    }

    /**
     * Gets the value of the idKorisnika property.
     * 
     */
    public long getIdKorisnika() {
        return idKorisnika;
    }

    /**
     * Sets the value of the idKorisnika property.
     * 
     */
    public void setIdKorisnika(long value) {
        this.idKorisnika = value;
    }

}
