//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 05:22:51 PM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="tipoviSmestaja" type="{http://booking.xml.com/backendmain/ws-classes}tipSmestajaXML" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="kategorijaSmestaja" type="{http://booking.xml.com/backendmain/ws-classes}kategorijaSmestajaXML" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tipoviSmestaja",
    "kategorijaSmestaja"
})
@XmlRootElement(name = "getDBResponse")
public class GetDBResponse {

    protected List<TipSmestajaXML> tipoviSmestaja;
    protected List<KategorijaSmestajaXML> kategorijaSmestaja;

    /**
     * Gets the value of the tipoviSmestaja property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tipoviSmestaja property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTipoviSmestaja().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TipSmestajaXML }
     * 
     * 
     */
    public List<TipSmestajaXML> getTipoviSmestaja() {
        if (tipoviSmestaja == null) {
            tipoviSmestaja = new ArrayList<TipSmestajaXML>();
        }
        return this.tipoviSmestaja;
    }

    /**
     * Gets the value of the kategorijaSmestaja property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the kategorijaSmestaja property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getKategorijaSmestaja().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link KategorijaSmestajaXML }
     * 
     * 
     */
    public List<KategorijaSmestajaXML> getKategorijaSmestaja() {
        if (kategorijaSmestaja == null) {
            kategorijaSmestaja = new ArrayList<KategorijaSmestajaXML>();
        }
        return this.kategorijaSmestaja;
    }
}
