//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 05:31:07 PM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.xml.booking.backendmain.ws_classes package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.xml.booking.backendmain.ws_classes
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link KorisnikRequest }
     * 
     */
    public KorisnikRequest createKorisnikRequest() {
        return new KorisnikRequest();
    }

    /**
     * Create an instance of {@link KorisnikXML }
     * 
     */
    public KorisnikXML createKorisnikXML() {
        return new KorisnikXML();
    }

    /**
     * Create an instance of {@link KorisnikResponse }
     * 
     */
    public KorisnikResponse createKorisnikResponse() {
        return new KorisnikResponse();
    }

    /**
     * Create an instance of {@link PorukaRequest }
     * 
     */
    public PorukaRequest createPorukaRequest() {
        return new PorukaRequest();
    }

    /**
     * Create an instance of {@link PorukaXML }
     * 
     */
    public PorukaXML createPorukaXML() {
        return new PorukaXML();
    }

    /**
     * Create an instance of {@link PotvrdiResponse }
     * 
     */
    public PotvrdiResponse createPotvrdiResponse() {
        return new PotvrdiResponse();
    }

    /**
     * Create an instance of {@link RezXML }
     * 
     */
    public RezXML createRezXML() {
        return new RezXML();
    }

    /**
     * Create an instance of {@link PonudaResponse }
     * 
     */
    public PonudaResponse createPonudaResponse() {
        return new PonudaResponse();
    }

    /**
     * Create an instance of {@link PonudaXML }
     * 
     */
    public PonudaXML createPonudaXML() {
        return new PonudaXML();
    }

    /**
     * Create an instance of {@link GetDBRequest }
     * 
     */
    public GetDBRequest createGetDBRequest() {
        return new GetDBRequest();
    }

    /**
     * Create an instance of {@link ZauzetostRequest }
     * 
     */
    public ZauzetostRequest createZauzetostRequest() {
        return new ZauzetostRequest();
    }

    /**
     * Create an instance of {@link ZauzetostXML }
     * 
     */
    public ZauzetostXML createZauzetostXML() {
        return new ZauzetostXML();
    }

    /**
     * Create an instance of {@link ZauzetostResponse }
     * 
     */
    public ZauzetostResponse createZauzetostResponse() {
        return new ZauzetostResponse();
    }

    /**
     * Create an instance of {@link SmestajVlasnikResponse }
     * 
     */
    public SmestajVlasnikResponse createSmestajVlasnikResponse() {
        return new SmestajVlasnikResponse();
    }

    /**
     * Create an instance of {@link SmestajVlasnikXML }
     * 
     */
    public SmestajVlasnikXML createSmestajVlasnikXML() {
        return new SmestajVlasnikXML();
    }

    /**
     * Create an instance of {@link SmestajResponse }
     * 
     */
    public SmestajResponse createSmestajResponse() {
        return new SmestajResponse();
    }

    /**
     * Create an instance of {@link AccommodationXML }
     * 
     */
    public AccommodationXML createAccommodationXML() {
        return new AccommodationXML();
    }

    /**
     * Create an instance of {@link PotvrdiRequest }
     * 
     */
    public PotvrdiRequest createPotvrdiRequest() {
        return new PotvrdiRequest();
    }

    /**
     * Create an instance of {@link SmestajRequest }
     * 
     */
    public SmestajRequest createSmestajRequest() {
        return new SmestajRequest();
    }

    /**
     * Create an instance of {@link SmestajVlasnikRequest }
     * 
     */
    public SmestajVlasnikRequest createSmestajVlasnikRequest() {
        return new SmestajVlasnikRequest();
    }

    /**
     * Create an instance of {@link PonudaRequest }
     * 
     */
    public PonudaRequest createPonudaRequest() {
        return new PonudaRequest();
    }

    /**
     * Create an instance of {@link LogInResponse }
     * 
     */
    public LogInResponse createLogInResponse() {
        return new LogInResponse();
    }

    /**
     * Create an instance of {@link UserXML }
     * 
     */
    public UserXML createUserXML() {
        return new UserXML();
    }

    /**
     * Create an instance of {@link LogInRequest }
     * 
     */
    public LogInRequest createLogInRequest() {
        return new LogInRequest();
    }

    /**
     * Create an instance of {@link PorukaResponse }
     * 
     */
    public PorukaResponse createPorukaResponse() {
        return new PorukaResponse();
    }

    /**
     * Create an instance of {@link GetDBResponse }
     * 
     */
    public GetDBResponse createGetDBResponse() {
        return new GetDBResponse();
    }

    /**
     * Create an instance of {@link TipSmestajaXML }
     * 
     */
    public TipSmestajaXML createTipSmestajaXML() {
        return new TipSmestajaXML();
    }

    /**
     * Create an instance of {@link KategorijaSmestajaXML }
     * 
     */
    public KategorijaSmestajaXML createKategorijaSmestajaXML() {
        return new KategorijaSmestajaXML();
    }

    /**
     * Create an instance of {@link UslugaXML }
     * 
     */
    public UslugaXML createUslugaXML() {
        return new UslugaXML();
    }

    /**
     * Create an instance of {@link PonudauslugaXML }
     * 
     */
    public PonudauslugaXML createPonudauslugaXML() {
        return new PonudauslugaXML();
    }

    /**
     * Create an instance of {@link ChatXML }
     * 
     */
    public ChatXML createChatXML() {
        return new ChatXML();
    }

    /**
     * Create an instance of {@link ChatKorisnikXML }
     * 
     */
    public ChatKorisnikXML createChatKorisnikXML() {
        return new ChatKorisnikXML();
    }

    /**
     * Create an instance of {@link RezervacijaXML }
     * 
     */
    public RezervacijaXML createRezervacijaXML() {
        return new RezervacijaXML();
    }

    /**
     * Create an instance of {@link TestRequest }
     * 
     */
    public TestRequest createTestRequest() {
        return new TestRequest();
    }

    /**
     * Create an instance of {@link TestResponse }
     * 
     */
    public TestResponse createTestResponse() {
        return new TestResponse();
    }

    /**
     * Create an instance of {@link SlikaXML }
     * 
     */
    public SlikaXML createSlikaXML() {
        return new SlikaXML();
    }

}
