//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 12:43:00 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://booking.xml.com/backendmain/ws-classes", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.xml.booking.backendmain.ws_classes;
