//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.23 at 12:10:23 AM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="svRequest" type="{http://booking.xml.com/backendmain/ws-classes}smestajVlasnikXML"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "svRequest"
})
@XmlRootElement(name = "smestajVlasnikRequest")
public class SmestajVlasnikRequest {

    @XmlElement(required = true)
    protected SmestajVlasnikXML svRequest;

    /**
     * Gets the value of the svRequest property.
     * 
     * @return
     *     possible object is
     *     {@link SmestajVlasnikXML }
     *     
     */
    public SmestajVlasnikXML getSvRequest() {
        return svRequest;
    }

    /**
     * Sets the value of the svRequest property.
     * 
     * @param value
     *     allowed object is
     *     {@link SmestajVlasnikXML }
     *     
     */
    public void setSvRequest(SmestajVlasnikXML value) {
        this.svRequest = value;
    }

}
