//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.22 at 12:43:00 PM CEST 
//


package com.xml.booking.backendmain.ws_classes;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="zauzetost" type="{http://booking.xml.com/backendmain/ws-classes}zauzetostXML"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "zauzetost"
})
@XmlRootElement(name = "zauzetostRequest")
public class ZauzetostRequest {

    @XmlElement(required = true)
    protected ZauzetostXML zauzetost;

    /**
     * Gets the value of the zauzetost property.
     * 
     * @return
     *     possible object is
     *     {@link ZauzetostXML }
     *     
     */
    public ZauzetostXML getZauzetost() {
        return zauzetost;
    }

    /**
     * Sets the value of the zauzetost property.
     * 
     * @param value
     *     allowed object is
     *     {@link ZauzetostXML }
     *     
     */
    public void setZauzetost(ZauzetostXML value) {
        this.zauzetost = value;
    }

}
