//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 11:36:44 AM CEST 
//


package pi.vezbe.model;

import java.util.Date;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="datumObjave" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element ref="{}Smestaj"/>
 *         &lt;element name="opis">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;maxLength value="300"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="objavljen" type="{http://www.w3.org/2001/XMLSchema}boolean"/>
 *         &lt;element name="autor" type="{}Krajnji_korisnik"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "id",
    
    //"smestaj",
    "datumKomentara",
    "opis",
    "objavljen"
  //  "autor"
})
@XmlRootElement(name = "Komentar")
@Entity
public class Komentar {
	
	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
    protected long id;
   
	/*@ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "id_smestaja", nullable = false)
    @XmlElement(name = "Smestaj", required = true)
    protected Smestaj smestaj;*/
	
	@XmlElement(required = true)
    @XmlSchemaType(name = "date")
    protected Date datumKomentara;
	
	
    @XmlElement(required = true)
    protected String opis;
    protected boolean objavljen;
    
   
    /*@XmlElement(required = true)
    protected KrajnjiKorisnik autor;*/

    /**
     * Gets the value of the id property.
     * 
     */
    public long getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(long value) {
        this.id = value;
    }

   

    public Date getDatumKomentara() {
		return datumKomentara;
	}

	public void setDatumKomentara(Date datumKomentara) {
		this.datumKomentara = datumKomentara;
	}

	/**
     * Gets the value of the smestaj property.
     * 
     * @return
     *     possible object is
     *     {@link Smestaj }
     *     
     */
  /*  public Smestaj getSmestaj() {
        return smestaj;
    }*/

    /**
     * Sets the value of the smestaj property.
     * 
     * @param value
     *     allowed object is
     *     {@link Smestaj }
     *     
     */
  /*  public void setSmestaj(Smestaj value) {
        this.smestaj = value;
    }*/

    /**
     * Gets the value of the opis property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOpis() {
        return opis;
    }

    /**
     * Sets the value of the opis property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOpis(String value) {
        this.opis = value;
    }

    /**
     * Gets the value of the objavljen property.
     * 
     */
    public boolean isObjavljen() {
        return objavljen;
    }

    /**
     * Sets the value of the objavljen property.
     * 
     */
    public void setObjavljen(boolean value) {
        this.objavljen = value;
    }

    /**
     * Gets the value of the autor property.
     * 
     * @return
     *     possible object is
     *     {@link KrajnjiKorisnik }
     *     
     */
   

}
