//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.05.23 at 11:36:44 AM CEST 
//


package pi.vezbe.model;

import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Krajnji_korisnik complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Krajnji_korisnik">
 *   &lt;complexContent>
 *     &lt;extension base="{}Korisnik">
 *       &lt;attribute name="blokiran" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Krajnji_korisnik")
@Entity
public class KrajnjiKorisnik
    extends Korisnik
{
	//@XmlElement(name = "Komentari", required = true)
    //@OneToMany(mappedBy = "autor", cascade = CascadeType.REMOVE)
	//protected List<Komentar> komentari;
	
    @XmlAttribute(name = "blokiran")
    protected Boolean blokiran;

    /**
     * Gets the value of the blokiran property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBlokiran() {
        return blokiran;
    }
    
    @OneToMany(mappedBy="korisnik", cascade = CascadeType.REMOVE)
	private List<Rezervacija> rezervacije;
    
    

  /*  public List<Komentar> getKomentari() {
		return komentari;
	}



	public void setKomentari(List<Komentar> komentari) {
		this.komentari = komentari;
	}
*/


	public Boolean getBlokiran() {
		return blokiran;
	}



	/**
     * Sets the value of the blokiran property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlokiran(Boolean value) {
        this.blokiran = value;
    }

	public KrajnjiKorisnik(Long id, String ime, String prezime, String email, String lozinka, String kontakt, Boolean blokiran) {
		super(id, ime, prezime, email, lozinka, kontakt, Role.REGISTERED);
		this.blokiran = blokiran;
	}
    
	public KrajnjiKorisnik() {
		this.setRole(Role.REGISTERED);
	}



	public List<Rezervacija> getRezervacije() {
		return rezervacije;
	}



	public void setRezervacije(List<Rezervacija> rezervacije) {
		this.rezervacije = rezervacije;
	}
	
	
}
