/// <autosync enabled="true" />
/// <reference path="../client scripts/mvcfoolproof.unobtrusive.min.js" />
/// <reference path="../client scripts/mvcfoolproofjqueryvalidation.min.js" />
/// <reference path="../client scripts/mvcfoolproofvalidation.min.js" />
/// <reference path="../client scripts/setupmap.js" />
/// <reference path="ai.0.22.9-build00167.min.js" />
/// <reference path="bootstrap.js" />
/// <reference path="canvasjs.min.js" />
/// <reference path="jquery.seat-charts.js" />
/// <reference path="jquery.seat-charts2.js" />
/// <reference path="jquery.unobtrusive-ajax.js" />
/// <reference path="jquery.validate.js" />
/// <reference path="jquery.validate.unobtrusive.min.js" />
/// <reference path="jquery-1.10.2.js" />
/// <reference path="jquery-1.12.4.js" />
/// <reference path="jquery-1.12.4.min.js" />
/// <reference path="jquery-ui-1.12.1.js" />
/// <reference path="jquery-ui-1.12.1.min.js" />
/// <reference path="modernizr-2.6.2.js" />
/// <reference path="respond.js" />
